### PR TITLE
Instead of logging stack traces to std.err catch the exception and pr…

### PR DESCRIPTION
**Pull request by csutherl**
…int a helpful message for users

### CODE REVIEW

**Comment by jfclere** [comment]
I am not that removing the stack traces output is good... And there is 2 fixes in the commit (the filtering input I want to merge).

**Comment by csutherl** [comment]
> I am not that removing the stack traces output is good... 

Why not? While stack traces are good for developers a message telling the user what they did wrong is better for CLI tools in my experience. I could be wrong, but I can't say that I've ever seen a CLI tool that threw a stack trace when there was an error.

> And there is 2 fixes in the commit (the filtering input I want to merge).

I included that on it's on in #21. This commit still updates the message and doesn't print the stack trace that the other PR adds.

**Comment by jfclere** [comment]
Well in fact I would like to be able to debug the exception, but that doesn't make sense, sorry.
Can you fix the conflicts and resubmit the PR.

**Comment by csutherl** [comment]
> Well in fact I would like to be able to debug the exception, but that doesn't make sense, sorry.

I'm trying to make it easier for end users to see the issue. Stack traces usually scare people that aren't developers. If you want, we could add a debug argument that prints more verbose logging and stack traces on errors?

> Can you fix the conflicts and resubmit the PR.

Yep, done.

**Pull request merged**
