### PR TITLE
JWS-248 and JWS-217

### PR DESCRIPTION
**Pull request by S4n60w3n**
Loot at commit messages

### CODE REVIEW

**Comment by S4n60w3n** [comment]
@jfclere

**Comment by jfclere** [comment]
Can't you stash those 6 commits into one, there is no way I will the stuff otherwise.

**Comment by jfclere** [comment]
Additionally why do you rename the bat and shell scripts?

**Comment by S4n60w3n** [comment]
Rename was because of postinstall which need to have this name of script. I`ll stash those cocmmits, i leave it in 6 so it is better to see what was changed for JIRAS and for revision

**Comment by jfclere** [comment]
then you need to fix the postinstall there is not reasons to change scripts names.

**Pull request closed without merging**
